<a href="https://colab.research.google.com/github/Sharan-Prasath/Week2-Logistics-Preprocessing/blob/main/week2_preprocessing.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import pandas as pd

df = pd.read_csv('dynamic_supply_chain_logistics_dataset_with_country.csv')

In [2]:
print(df.shape)
print(df.columns)
df.head()

(113097, 18)
Index(['warehouse_inventory_level', 'handling_equipment_availability',
       'order_fulfillment_status', 'weather_condition_severity',
       'shipping_costs', 'supplier_reliability_score', 'lead_time_days',
       'historical_demand', 'cargo_condition_status', 'route_risk_level',
       'customs_clearance_time', 'disruption_likelihood_score',
       'delay_probability', 'risk_classification', 'delivery_time_deviation',
       'product_id', 'supplier_id', 'supplier_country'],
      dtype='object')

,warehouse_inventory_level,handling_equipment_availability,order_fulfillment_status,weather_condition_severity,shipping_costs,supplier_reliability_score,lead_time_days,historical_demand,cargo_condition_status,route_risk_level,customs_clearance_time,disruption_likelihood_score,delay_probability,risk_classification,delivery_time_deviation,product_id,supplier_id,supplier_country
0,985.716862,0.481294,0.761166,0.359066,456.503853,0.986064,2.128009,100.772854,0.777263,1.182116,0.502006,0.506152,0.885291,Moderate Risk,9.110682,P0353,P0353_S1,Greece
1,985.716862,0.481294,0.761166,0.359066,456.503853,0.986064,2.128009,100.772854,0.777263,1.182116,0.502006,0.506152,0.885291,Moderate Risk,9.110682,P0353,P0353_S2,South Korea
2,985.716862,0.481294,0.761166,0.359066,456.503853,0.986064,2.128009,100.772854,0.777263,1.182116,0.502006,0.506152,0.885291,Moderate Risk,9.110682,P0353,P0353_S3,Ethiopia
3,396.700206,0.620780,0.196594,0.230660,640.408205,0.463233,12.608166,5313.738114,0.091839,9.611988,0.966774,0.980784,0.544178,High Risk,8.175281,P0857,P0857_S1,Iran
4,396.700206,0.620780,0.196594,0.230660,640.408205,0.463233,12.608166,5313.738114,0.091839,9.611988,0.966774,0.980784,0.544178,High Risk,8.175281,P0857,P0857_S2,Guatemala

In [3]:
df.info()
df.isnull().sum()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 113097 entries, 0 to 113096
Data columns (total 18 columns):
 #   Column                           Non-Null Count   Dtype
---  ------                           --------------   -----
 0   warehouse_inventory_level        113097 non-null  float64
 1   handling_equipment_availability  113097 non-null  float64
 2   order_fulfillment_status         113097 non-null  float64
 3   weather_condition_severity       113097 non-null  float64
 4   shipping_costs                   113097 non-null  float64
 5   supplier_reliability_score       113097 non-null  float64
 6   lead_time_days                   113097 non-null  float64
 7   historical_demand                113097 non-null  float64
 8   cargo_condition_status           113097 non-null  float64
 9   route_risk_level                 113097 non-null  float64
 10  customs_clearance_time           113097 non-null  float64
 11  disruption_likelihood_score      113097 non-null  float64
 12  delay_probability                113097 non-null  float64
 13  risk_classification              113097 non-null  object
 14  delivery_time_deviation          113097 non-null  float64
 15  product_id                       113097 non-null  object
 16  supplier_id                      113097 non-null  object
 17  supplier_country                 113097 non-null  object
dtypes: float64(14), object(4)
memory usage: 15.5+ MB

warehouse_inventory_level          0
handling_equipment_availability    0
order_fulfillment_status           0
weather_condition_severity         0
shipping_costs                     0
supplier_reliability_score         0
lead_time_days                     0
historical_demand                  0
cargo_condition_status             0
route_risk_level                   0
customs_clearance_time             0
disruption_likelihood_score        0
delay_probability                  0
risk_classification                0
delivery_time_deviation            0
product_id                         0
supplier_id                        0
supplier_country                   0
dtype: int64

In [4]:
print(df.isnull().sum())

warehouse_inventory_level          0
handling_equipment_availability    0
order_fulfillment_status           0
weather_condition_severity         0
shipping_costs                     0
supplier_reliability_score         0
lead_time_days                     0
historical_demand                  0
cargo_condition_status             0
route_risk_level                   0
customs_clearance_time             0
disruption_likelihood_score        0
delay_probability                  0
risk_classification                0
delivery_time_deviation            0
product_id                         0
supplier_id                        0
supplier_country                   0
dtype: int64

In [5]:
df.fillna(df.median(numeric_only=True), inplace=True)

In [6]:
df.drop_duplicates(inplace=True)

In [8]:
duplicates = df.duplicated().sum()
print("Duplicate rows:", duplicates)

df = df.drop_duplicates()

Duplicate rows: 0

In [9]:
Q1 = df['shipping_costs'].quantile(0.25)
Q3 = df['shipping_costs'].quantile(0.75)

IQR = Q3 - Q1

lower = Q1 - 1.5 * IQR
upper = Q3 + 1.5 * IQR

outliers = df[(df['shipping_costs'] < lower) |
              (df['shipping_costs'] > upper)]

print("Outliers:", len(outliers))

Outliers: 0

In [10]:
from sklearn.preprocessing import MinMaxScaler

scaler = MinMaxScaler()

cols = [
    'warehouse_inventory_level',
    'shipping_costs',
    'supplier_reliability_score',
    'lead_time_days',
    'historical_demand'
]

df[cols] = scaler.fit_transform(df[cols])

In [11]:
from sklearn.preprocessing import LabelEncoder

le = LabelEncoder()

df['risk_classification'] = le.fit_transform(
    df['risk_classification']
)

df['supplier_country'] = le.fit_transform(
    df['supplier_country']
)

In [12]:
df.to_csv("cleaned_logistics_dataset.csv", index=False)